// File generated by Antigravity.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_data_only
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOYfgXenbLf1iAYJpfdK93csSjuxLiUTw',
    appId: '1:567289849566:web:98d1e0209eedf43dbe444f',
    messagingSenderId: '567289849566',
    projectId: 'tameenidz-official-prod',
    authDomain: 'tameenidz-official-prod.firebaseapp.com',
    storageBucket: 'tameenidz-official-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1J2PDNJ05fouIsEMGYFFpg9-6qARlXMc',
    appId: '1:567289849566:android:56ba5f17871a0490be444f',
    messagingSenderId: '567289849566',
    projectId: 'tameenidz-official-prod',
    storageBucket: 'tameenidz-official-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOY4YacYP3019-cAMi1hRkZym5Pum40w',
    appId: '1:567289849566:ios:52973f5da53faa2cbe444f',
    messagingSenderId: '567289849566',
    projectId: 'tameenidz-official-prod',
    storageBucket: 'tameenidz-official-prod.firebasestorage.app',
    iosBundleId: 'com.example.tameenidz',
  );
}
